spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    content-type: text/html
  resources:
    chain:
      strategy:
        content:
          paths: /**
      enabled: true

  datasource:
    username: root
    password: yjf948512
    url: jdbc:mysql://47.107.36.143:3306/tech
    driver-class-name: com.mysql.jdbc.Driver
  freemarker:
    cache: false
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  session:
    store-type: none

security:
  basic:
    enabled: false



server:
  port: 8080

